#include "web_ui.h"
#include "configuration.h"

#include "esp_http_server.h"
#include "esp_log.h"

static const char *TAG = "webui";

static const char *PAGE_SHELL_HEAD =
    "<!DOCTYPE html><html><head><meta charset=utf-8>"
    "<meta name=viewport content=\"width=device-width,initial-scale=1\">"
    "<title>WakeType</title>"
    "<style>"
    ":root{--bg:#0e131a;--card:#171e28;--line:#2a3544;--text:#e8eef5;--muted:#93a1b3;--accent:#3b82f6;--ok:#34d399;--warn:#fbbf24;--bad:#f87171}"
    "*{box-sizing:border-box}"
    "body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text);line-height:1.45}"
    "header{position:sticky;top:0;z-index:5;backdrop-filter:blur(8px);background:rgba(14,19,26,.92);border-bottom:1px solid var(--line);padding:.9rem 1.1rem;display:flex;gap:1rem;align-items:center;justify-content:space-between;flex-wrap:wrap}"
    "header .brand{font-weight:700;letter-spacing:.02em}"
    "nav{display:flex;gap:.35rem}"
    "nav a{color:var(--muted);text-decoration:none;padding:.4rem .7rem;border-radius:999px;font-size:.92rem}"
    "nav a.active,nav a:hover{background:var(--card);color:var(--text)}"
    "main{padding:1.1rem;max-width:760px;margin:0 auto}"
    "section{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:1rem 1.1rem;margin:0 0 1rem}"
    "h1{font-size:1.15rem;margin:0 0 .35rem}h2{font-size:1rem;margin:0 0 .75rem}"
    "p.lead{color:var(--muted);margin:.2rem 0 0;font-size:.92rem}"
    "label{display:block;margin:.65rem 0 .25rem;font-size:.82rem;color:var(--muted)}"
    "input,select,button,textarea{width:100%;padding:.65rem .75rem;border-radius:10px;border:1px solid var(--line);background:#0f1520;color:var(--text);font:inherit}"
    "button{cursor:pointer;background:var(--accent);border:none;font-weight:650;margin-top:.55rem}"
    "button.secondary{background:#2b3646}button.danger{background:#b91c1c}"
    ".row{display:flex;gap:.5rem;flex-wrap:wrap}.row>*{flex:1;min-width:120px}"
    "dl{display:grid;grid-template-columns:8.5rem 1fr;gap:.4rem .8rem;margin:0;font-size:.92rem}"
    "dt{color:var(--muted)}dd{margin:0;word-break:break-all}"
    ".banner{padding:.75rem .9rem;border-radius:10px;margin:0 0 .8rem;font-size:.9rem}"
    ".banner.ok{background:rgba(52,211,153,.12);color:var(--ok)}.banner.warn{background:rgba(251,191,36,.12);color:var(--warn)}"
    ".banner.bad{background:rgba(248,113,113,.12);color:var(--bad)}"
    ".pill{display:inline-block;padding:.15rem .55rem;border-radius:999px;font-size:.75rem;background:#243041;color:var(--muted)}"
    ".pill.on{background:rgba(52,211,153,.15);color:var(--ok)}.pill.off{background:rgba(248,113,113,.12);color:var(--bad)}"
    "details{margin-top:.75rem}summary{cursor:pointer;color:var(--muted)}"
    "pre{white-space:pre-wrap;font-size:.78rem;background:#0b1016;padding:.7rem;border-radius:8px;overflow:auto}"
    "small{color:var(--muted)}"
    ".keybox{display:flex;gap:.5rem;align-items:stretch}.keybox input{flex:1}"
    ".keybox button{width:auto;margin-top:0;padding:.65rem .9rem}"
    "</style>"
    "<script>"
    "const TKEY='waketype_device_key';"
    "function tok(){return localStorage.getItem(TKEY)||''}"
    "function setTok(t){t=(t||'').trim(); if(!t) return false; localStorage.setItem(TKEY,t);"
    "  document.querySelectorAll('#deviceKey,#token').forEach(e=>{if(e)e.value=t}); return true;}"
    "function absorbKeyFromUrl(){"
    "  const u=new URL(location.href);"
    "  const k=u.searchParams.get('key')||u.searchParams.get('token');"
    "  if(k){setTok(k); u.searchParams.delete('key'); u.searchParams.delete('token');"
    "    history.replaceState({},'',u.pathname+(u.search||'')+u.hash); return true;}"
    "  return false;"
    "}"
    "absorbKeyFromUrl();"
    "async function api(path,opt={}){"
    "  const h=Object.assign({'Content-Type':'application/json'},opt.headers||{});"
    "  if(tok()) h['Authorization']='Bearer '+tok();"
    "  const r=await fetch(path,Object.assign({},opt,{headers:h}));"
    "  const t=await r.text(); let j=null; try{j=JSON.parse(t)}catch(e){}"
    "  if(!r.ok){const err=new Error((j&&(j.hint||j.error))||t||('HTTP '+r.status)); err.status=r.status; err.body=j; throw err;}"
    "  if(j&&(j.device_key||j.api_token)) setTok(j.device_key||j.api_token);"
    "  return j;"
    "}"
    "function setDl(dl,rows){if(!dl)return; dl.innerHTML=''; rows.forEach(([k,v])=>{const dt=document.createElement('dt');dt.textContent=k;"
    "  const dd=document.createElement('dd');dd.textContent=(v==null||v==='')?'—':String(v); dl.appendChild(dt); dl.appendChild(dd);});}"
    "function banner(id,text,cls){const el=document.getElementById(id); if(!el)return; el.className='banner '+(cls||''); el.textContent=text||''; el.style.display=text?'block':'none'}"
    "function markNav(){const p=location.pathname; [['navHome','/'],['navSettings','/settings'],['navOta','/ota']].forEach(([id,path])=>{const a=document.getElementById(id); if(a) a.classList.toggle('active', p===path);});}"
    "document.addEventListener('DOMContentLoaded',()=>{"
    "  markNav();"
    "  document.querySelectorAll('#deviceKey').forEach(el=>{"
    "    if(tok() && !el.value) el.value=tok();"
    "    el.addEventListener('change',()=>setTok(el.value));"
    "    el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault(); setTok(el.value);}});"
    "  });"
    "});"
    "</script></head><body>"
    "<header><div class=brand>WakeType</div><nav>"
    "<a id=navHome href=/>Home</a><a id=navSettings href=/settings>Settings</a><a id=navOta href=/ota>Update</a>"
    "</nav></header><main>";

static const char *PAGE_SHELL_FOOT =
    "</main></body></html>";

static esp_err_t send_html(httpd_req_t *req, const char *body)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_sendstr_chunk(req, PAGE_SHELL_HEAD);
    httpd_resp_sendstr_chunk(req, body);
    httpd_resp_sendstr_chunk(req, PAGE_SHELL_FOOT);
    return httpd_resp_sendstr_chunk(req, NULL);
}

static esp_err_t handle_home(httpd_req_t *req)
{
    return send_html(req,
        "<section>"
        "<h1>Home</h1>"
        "<p class=lead>Power / reset controls and live status. Wi‑Fi lives under <a href=/settings style=color:#8ec7ff>Settings</a>.</p>"
        "<div id=authBanner class=banner warn style=display:none></div>"
        "<div style=\"margin-top:.9rem;display:flex;gap:.5rem;align-items:center;flex-wrap:wrap\">"
        "<span class=pill id=connPill>…</span>"
        "<span class=pill id=pcPill>PC …</span>"
        "</div>"
        "<dl id=sumDl style=\"margin-top:.9rem\"></dl>"
        "<div class=row style=\"margin-top:.5rem\">"
        "<button class=secondary onclick=\"refresh()\">Refresh</button>"
        "<a href=/settings style=\"flex:1\"><button class=secondary style=\"width:100%\">Wi‑Fi &amp; settings</button></a>"
        "</div>"
        "</section>"
        "<section>"
        "<h2>PC controls</h2>"
        "<p class=lead>Safe for dry-testing with relays not wired to the motherboard.</p>"
        "<div class=row>"
        "<button onclick=\"pc('/api/v1/pc/power')\">Power press</button>"
        "<button class=danger onclick=\"if(confirm('Hold power button ~5 seconds?'))pc('/api/v1/pc/power/hold',{duration_ms:5000})\">Long hold</button>"
        "</div>"
        "<div class=row>"
        "<button class=danger onclick=\"if(confirm('Reset the PC?'))pc('/api/v1/pc/reset')\">Reset</button>"
        "<button class=secondary onclick=\"pc('/api/v1/pc/release')\">Release relays</button>"
        "</div>"
        "<div id=pcmsg class=banner style=display:none;margin-top:.75rem></div>"
        "</section>"
        "<script>"
        "async function refresh(){"
        "  try{"
        "    const j=await api('/api/v1/status');"
        "    banner('authBanner','','');"
        "    connPill.textContent=j.wifi_connected?('Wi‑Fi: '+(j.wifi_ssid||'connected')):(j.setup_mode?'Setup hotspot':'Wi‑Fi: offline');"
        "    connPill.className='pill '+(j.wifi_connected?'on':(j.setup_mode?'warn':'off'));"
        "    pcPill.textContent='PC: '+(j.pc_state||'?');"
        "    pcPill.className='pill '+(j.pc_state==='ON'?'on':(j.pc_state==='OFF'?'off':''));"
        "    setDl(sumDl,["
        "      ['Sense pin', j.pc_state_gpio!=null?('GPIO '+j.pc_state_gpio):'—'],"
        "      ['Network', j.wifi_ssid||'—'],"
        "      ['IP', j.ip||'—'],"
        "      ['Mode', j.wifi_mode+(j.wifi_use_static?' · static':' · DHCP')],"
        "      ['Signal', j.rssi!=null?(j.rssi+' dBm'):'—'],"
        "      ['Firmware', j.firmware]"
        "    ]);"
        "    if(j.setup_mode) banner('authBanner','Setup mode: join this hotspot, then open Settings to pick your home Wi‑Fi.','warn');"
        "  }catch(e){"
        "    banner('authBanner', e.message||'Need device key — open Settings.','bad');"
        "  }"
        "}"
        "async function pc(path,body){"
        "  try{const j=await api(path,{method:'POST',body:body?JSON.stringify(body):'{}'});"
        "    banner('pcmsg', j.ok?'Done.':'Error: '+(j.error||''), j.ok?'ok':'bad'); refresh();}"
        "  catch(e){banner('pcmsg', e.message,'bad');}"
        "}"
        "refresh(); setInterval(refresh,2000);"
        "</script>");
}

static esp_err_t handle_settings(httpd_req_t *req)
{
    return send_html(req,
        "<section>"
        "<h1>Settings</h1>"
        "<p class=lead>Wi‑Fi, network address, and device options — all in one place.</p>"
        "<div id=authBanner class=banner warn style=display:none></div>"
        "</section>"

        "<section>"
        "<h2>Device key</h2>"
        "<p class=lead>Password for this board. Saved in this browser after you enter it "
        "(and your browser may offer to remember it). Paste again only on a new device/browser.</p>"
        "<form id=keyForm onsubmit=\"event.preventDefault(); if(setTok(deviceKey.value)){banner('keyMsg','Saved in this browser','ok'); load();} else banner('keyMsg','Enter a key first','bad');\">"
        "<input type=text name=username autocomplete=username value=WakeType style=display:none aria-hidden=true tabindex=-1>"
        "<div class=keybox>"
        "<input id=deviceKey name=password type=password autocomplete=current-password placeholder=\"Paste device key\">"
        "<button class=secondary type=submit>Save</button>"
        "<button class=secondary type=button onclick=\"deviceKey.type=deviceKey.type==='password'?'text':'password'\">Show</button>"
        "</div>"
        "</form>"
        "<div class=row>"
        "<button class=secondary type=button onclick=\"navigator.clipboard.writeText(tok());banner('keyMsg','Copied','ok')\">Copy</button>"
        "</div>"
        "<div id=keyMsg class=banner style=display:none></div>"
        "<small>Tip: open <code>/settings?key=YOUR_KEY</code> once to load it. "
        "Note: <code>waketype.local</code> and a raw IP are different sites to the browser — each needs the key once.</small>"
        "</section>"

        "<section>"
        "<h2>Wi‑Fi</h2>"
        "<dl id=wifiDl></dl>"
        "<h2 style=\"margin-top:1.1rem\">Change network</h2>"
        "<div class=row>"
        "<button class=secondary type=button onclick=\"scan()\">Scan networks</button>"
        "</div>"
        "<label>Choose network</label><select id=ssidList><option value=\"\">— scan first —</option></select>"
        "<label>Or type SSID</label><input id=ssidManual placeholder=\"Network name\">"
        "<label>Password</label><input id=pass name=wifi-password type=password autocomplete=new-password placeholder=\"Wi‑Fi password\">"
        "<button type=button onclick=\"saveWifi()\">Connect to this network</button>"
        "<div id=wifiMsg class=banner style=display:none></div>"
        "<small>After connecting, open <b>http://waketype.local/settings</b>. "
        "If this browser loses the key, use the link shown after connect (includes <code>?key=…</code>).</small>"
        "</section>"

        "<section>"
        "<h2>Hostname &amp; IP</h2>"
        "<label>Hostname (router / .local name)</label><input id=hostname>"
        "<label><input type=checkbox id=useStatic style=\"width:auto\"> Use a fixed (static) IP</label>"
        "<div id=staticFields>"
        "<label>IP</label><input id=ip>"
        "<label>Gateway</label><input id=gw>"
        "<label>Netmask</label><input id=mask value=\"255.255.255.0\">"
        "<label>DNS 1</label><input id=dns1>"
        "<label>DNS 2</label><input id=dns2>"
        "</div>"
        "<button type=button onclick=\"saveNet()\">Save network settings</button>"
        "<div id=netMsg class=banner style=display:none></div>"
        "</section>"

        "<section>"
        "<h2>GPIO pins</h2>"
        "<p class=lead>Which ESP32 pins drive the relays and PC817. Change here instead of rebuilding. "
        "Applies immediately — move your breadboard wires to match.</p>"
        "<div class=row>"
        "<div><label>POWER relay (IN1)</label><input id=gpioPwr type=number min=1 max=48></div>"
        "<div><label>RESET relay (IN2)</label><input id=gpioRst type=number min=1 max=48></div>"
        "<div><label>PC state (PC817)</label><input id=gpioSt type=number min=1 max=48></div>"
        "</div>"
        "<button type=button onclick=\"saveGpio()\">Save pins</button>"
        "<div id=gpioMsg class=banner style=display:none></div>"
        "<small>Defaults 4 / 5 / 6. Example alternate: 13 / 14 / 6. Avoid 19–20 (USB) and 33–37 (flash).</small>"
        "</section>"

        "<section>"
        "<h2>Power timings &amp; lock</h2>"
        "<label>Power press (ms)</label><input id=pwr type=number>"
        "<label>Reset press (ms)</label><input id=rst type=number>"
        "<label>Default long hold (ms)</label><input id=long type=number>"
        "<label><input type=checkbox id=lock style=\"width:auto\"> Local lock (block remote control)</label>"
        "<label><input type=checkbox id=lockApi style=\"width:auto\"> Lock also blocks API (except Release)</label>"
        "<button type=button onclick=\"saveMisc()\">Save</button>"
        "<div id=miscMsg class=banner style=display:none></div>"
        "</section>"

        "<section>"
        "<h2>Backup</h2>"
        "<div class=row>"
        "<button class=secondary type=button onclick=\"backup()\">Download config JSON</button>"
        "</div>"
        "<label>Restore JSON</label><textarea id=cfg rows=6></textarea>"
        "<label><input type=checkbox id=incSecrets style=\"width:auto\"> Include Wi‑Fi password / device key on restore</label>"
        "<label><input type=checkbox id=clearStatic checked style=\"width:auto\"> Clear static IP on import</label>"
        "<button type=button onclick=\"restore()\">Restore</button>"
        "<div id=cfgMsg class=banner style=display:none></div>"
        "</section>"

        "<script>"
        "if(tok()) deviceKey.value=tok();"
        "async function load(){"
        "  try{"
        "    const j=await api('/api/v1/settings');"
        "    banner('authBanner','','');"
        "    if(j.device_key||j.api_token){setTok(j.device_key||j.api_token); deviceKey.value=tok();}"
        "    setDl(wifiDl,["
        "      ['SSID', j.wifi_ssid||'(none)'],"
        "      ['Status', j.wifi_connected?'Connected':'Not connected'],"
        "      ['Mode', j.wifi_mode||'—'],"
        "      ['Current IP', j.current_ip],"
        "      ['Gateway', j.current_gateway],"
        "      ['Netmask', j.current_netmask],"
        "      ['DNS', (j.current_dns1||'—')+(j.current_dns2?', '+j.current_dns2:'')],"
        "      ['Password saved', j.wifi_password_set?'yes':'no']"
        "    ]);"
        "    hostname.value=j.hostname||'waketype';"
        "    useStatic.checked=!!j.wifi_use_static;"
        "    ip.value=j.wifi_ip||''; gw.value=j.wifi_gateway||'';"
        "    mask.value=j.wifi_netmask||'255.255.255.0';"
        "    dns1.value=j.wifi_dns1||''; dns2.value=j.wifi_dns2||'';"
        "    pwr.value=j.power_press_ms; rst.value=j.reset_press_ms; long.value=j.default_long_press_ms;"
        "    lock.checked=!!j.local_lock; lockApi.checked=!!j.local_lock_blocks_api;"
        "    gpioPwr.value=j.power_relay_gpio; gpioRst.value=j.reset_relay_gpio; gpioSt.value=j.pc_state_gpio;"
        "    if(j.wifi_ssid) ssidManual.value=j.wifi_ssid;"
        "  }catch(e){"
        "    banner('authBanner', e.message,'bad');"
        "  }"
        "}"
        "async function scan(){"
        "  try{"
        "    banner('wifiMsg','Scanning…','warn');"
        "    const j=await api('/api/v1/wifi/scan');"
        "    const sel=ssidList; sel.innerHTML='';"
        "    const aps=j.aps||[];"
        "    if(!aps.length){sel.innerHTML='<option value=\"\">(no networks found)</option>'; banner('wifiMsg','No networks found','warn'); return;}"
        "    aps.forEach(a=>{const o=document.createElement('option'); o.value=a.ssid; o.textContent=a.ssid+'  ('+a.rssi+' dBm)'; sel.appendChild(o);});"
        "    banner('wifiMsg','Found '+aps.length+' networks','ok');"
        "  }catch(e){banner('wifiMsg', e.message,'bad');}"
        "}"
        "async function saveWifi(){"
        "  const ssid=(ssidManual.value||ssidList.value||'').trim();"
        "  if(!ssid){banner('wifiMsg','Pick or type a network name','bad'); return;}"
        "  try{"
        "    banner('wifiMsg','Saving and connecting…','warn');"
        "    const j=await api('/api/v1/wifi/connect',{method:'POST',body:JSON.stringify({ssid,password:pass.value})});"
        "    const key=j.device_key||j.api_token||tok();"
        "    if(key) setTok(key);"
        "    const link='http://waketype.local/settings?key='+encodeURIComponent(key||'');"
        "    banner('wifiMsg','Saved \"'+ssid+'\". After it joins Wi‑Fi, open: '+link,'ok');"
        "  }catch(e){banner('wifiMsg', e.message,'bad');}"
        "}"
        "async function saveNet(){"
        "  try{await api('/api/v1/settings',{method:'POST',body:JSON.stringify({"
        "    hostname:hostname.value, wifi_use_static:useStatic.checked,"
        "    wifi_ip:ip.value, wifi_gateway:gw.value, wifi_netmask:mask.value,"
        "    wifi_dns1:dns1.value, wifi_dns2:dns2.value"
        "  })}); banner('netMsg','Saved','ok'); load();}catch(e){banner('netMsg',e.message,'bad');}"
        "}"
        "async function saveGpio(){"
        "  try{await api('/api/v1/settings',{method:'POST',body:JSON.stringify({"
        "    power_relay_gpio:+gpioPwr.value, reset_relay_gpio:+gpioRst.value, pc_state_gpio:+gpioSt.value"
        "  })}); banner('gpioMsg','Pins saved and applied — wire IN1/IN2 to match','ok'); load();}"
        "  catch(e){banner('gpioMsg',e.message,'bad');}"
        "}"
        "async function saveMisc(){"
        "  try{await api('/api/v1/settings',{method:'POST',body:JSON.stringify({"
        "    power_press_ms:+pwr.value, reset_press_ms:+rst.value, default_long_press_ms:+long.value,"
        "    local_lock:lock.checked, local_lock_blocks_api:lockApi.checked"
        "  })}); banner('miscMsg','Saved','ok');}catch(e){banner('miscMsg',e.message,'bad');}"
        "}"
        "async function backup(){try{const j=await api('/api/v1/config');"
        "  const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(j,null,2)],{type:'application/json'}));"
        "  a.download='waketype-config.json'; a.click(); banner('cfgMsg','Downloaded','ok');}catch(e){banner('cfgMsg',e.message,'bad');}}"
        "async function restore(){try{const body=JSON.parse(cfg.value);"
        "  body.clear_static_ip=clearStatic.checked; body.include_secrets=incSecrets.checked;"
        "  await api('/api/v1/config',{method:'POST',body:JSON.stringify(body)}); banner('cfgMsg','Restored','ok'); load();}"
        "  catch(e){banner('cfgMsg',e.message,'bad');}}"
        "load();"
        "</script>");
}

static esp_err_t handle_ota_page(httpd_req_t *req)
{
    return send_html(req,
        "<section>"
        "<h1>Firmware update</h1>"
        "<p class=lead>Upload a WakeType <code>.bin</code> over Wi‑Fi. Relays are forced OFF before flashing.</p>"
        "<div id=authBanner class=banner warn style=display:none></div>"
        "<label>Device key</label>"
        "<form id=keyForm onsubmit=\"event.preventDefault(); if(setTok(deviceKey.value)) banner('authBanner','Key saved','ok'); else banner('authBanner','Enter a key first','bad');\">"
        "<input type=text name=username autocomplete=username value=WakeType style=display:none aria-hidden=true tabindex=-1>"
        "<div class=keybox>"
        "<input id=deviceKey name=password type=password autocomplete=current-password placeholder=\"Paste if needed\">"
        "<button class=secondary type=submit>Save</button>"
        "</div>"
        "</form>"
        "<label>Firmware file</label>"
        "<input id=file type=file accept=.bin>"
        "<button class=danger type=button onclick=\"upload()\">Upload &amp; reboot</button>"
        "<div id=m class=banner style=display:none></div>"
        "</section>"
        "<script>"
        "if(tok()) deviceKey.value=tok();"
        "async function upload(){"
        "  const f=file.files[0]; if(!f){banner('m','Choose a .bin file','bad'); return;}"
        "  if(!tok()){banner('m','Save the device key first','bad'); return;}"
        "  banner('m','Uploading…','warn');"
        "  try{"
        "    const r=await fetch('/api/v1/ota',{method:'POST',headers:{Authorization:'Bearer '+tok(),'Content-Type':'application/octet-stream'},body:f});"
        "    const t=await r.text(); if(!r.ok) throw new Error(t); banner('m',t,'ok');"
        "  }catch(e){banner('m',e.message,'bad');}"
        "}"
        "</script>");
}

static esp_err_t handle_captive_redirect(httpd_req_t *req)
{
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", "http://192.168.4.1/settings");
    return httpd_resp_send(req, NULL, 0);
}

esp_err_t web_ui_register(httpd_handle_t server)
{
    const httpd_uri_t routes[] = {
        {.uri = "/", .method = HTTP_GET, .handler = handle_home},
        {.uri = "/settings", .method = HTTP_GET, .handler = handle_settings},
        {.uri = "/ota", .method = HTTP_GET, .handler = handle_ota_page},
        {.uri = "/generate_204", .method = HTTP_GET, .handler = handle_captive_redirect},
        {.uri = "/hotspot-detect.html", .method = HTTP_GET, .handler = handle_captive_redirect},
        {.uri = "/canonical.html", .method = HTTP_GET, .handler = handle_captive_redirect},
    };
    for (size_t i = 0; i < sizeof(routes) / sizeof(routes[0]); i++) {
        httpd_register_uri_handler(server, &routes[i]);
    }
    ESP_LOGI(TAG, "Web UI registered");
    return ESP_OK;
}
