# Append these items to /config/automations.yaml.
# If that file is `[]`, replace `[]` with this list.

- id: waketype_pc_controls_on
  alias: WakeType PC controls session start
  trigger:
    - platform: state
      entity_id: input_boolean.pc_controls
      to: "on"
  action:
    - service: timer.start
      target:
        entity_id: timer.pc_controls
      data:
        duration: "00:01:00"

- id: waketype_pc_controls_off
  alias: WakeType PC controls session end
  trigger:
    - platform: state
      entity_id: input_boolean.pc_controls
      to: "off"
  action:
    - service: timer.cancel
      target:
        entity_id: timer.pc_controls

- id: waketype_pc_controls_timeout
  alias: WakeType PC controls auto lock
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.pc_controls
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.pc_controls
